#include <iostream>
using namespace std;
main () {
int number1;
int number2;
int number3;
int number4;
int number5;
int number6;
int number7;
int number8;
int number9;
int number10;
int number11;
int number12;
int number13;
int number14;
int number15;
int add;
int multiply;
int subtracts;
int total;
cout << " Enter number 1: " ;
cin >> number1;
cout << " Enter number 2: " ;
cin >> number2;
cout << " Enter number 3: " ;
cin >> number3;
cout << " Enter number 4: " ;
cin >> number4;
cout << " Enter number 5: " ;
cin >> number5;
cout << " Enter number 6: " ;
cin >> number6;
cout << " Enter number 7: " ;
cin >> number7;
cout << " Enter number 8: " ;
cin >> number8;
cout << " Enter number 9: " ;
cin >> number9;
cout << " Enter number 10: " ;
cin >> number10;
cout << " Enter number 11: " ;
cin >> number11;
cout << " Enter number 12: " ;
cin >> number12;
cout << " Enter number 13: " ;
cin >> number13;
cout << " Enter number 14: " ;
cin >> number14;
cout << " Enter number 15: " ;
cin >> number15;
add=number1+number2+number3+number4+number5;
multiply=number6*number7*number8*number9*number10;
subtracts=number11-number12-number13-number14-number15;
total=add+multiply-subtracts;
cout << "Total: "<< total;
}